### ISSUE TITLE
RBAC doesn't support `Project Id` as params of Registry API calls.

### ISSUE THREAD

**Issue by jainr** [feathr-ai/feathr#669]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the Feathr community.

### Feathr version

0.7.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:

### Describe the problem

Trying to register features with RBAC enabled and get this error.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8405222/190115856-fc4b11a1-5004-4351-882a-307e0df7149e.png)

### Code to reproduce bug

```python
feathr_client.register_features()
```

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [X] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by Yuqing-cat** [comment]
I would prefer to call it a new feature rather than bug. 
Both `project name` and `project id` are unique in the registry. 
`GET` API calls used to send `project name` as params and RBAC works at that time. 

Now, all the API calls will take `project id` as params. 
As a result, RBAC need to add a new feature to be able to 
- support both project name and project id (UUID)
- recognize project name of a project id, which requires some change to backend registry APIs.
