### ISSUE TITLE
[BUG] When Feathr is running on databricks cluster, `get_result_df` should not download the result; it should use spark. spark.read.load

### ISSUE THREAD

**Issue by xiaoyongzhu** [feathr-ai/feathr#843]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

0.9

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:

### Describe the problem

When Feathr is running on databricks cluster, `get_result_df` should not download the result; it should use spark. spark.read.load.

Otherwise, `get_result_df` will try to "download" the data to "local" and just move data around, which doesn't make sense.

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by loomlike** [comment]
This function currently doesn't download if the target cluster is databricks and the `get_result_df` function is being called from databricks notebook. Following code snippet from the function shows it overrides `local_cache_path` to use `res_url` (and thus will not download).

```
elif client.spark_runtime == "databricks":
        if not res_url.startswith("dbfs:"):
            logger.warning(
                f"In Databricks, the result files are expected to be stored in DBFS, but the res_url {res_url} is not a dbfs path. Prefixing it with 'dbfs:/'"
            )
            res_url = f"dbfs:/{res_url.lstrip('/')}"

        if is_databricks():  # Check if the function is being called from Databricks
            if local_cache_path is not None:
                logger.warning(
                    "Result files are already in DBFS and thus `local_cache_path` will be ignored."
                )
            local_cache_path = res_url

...

if local_cache_path != res_url:
        logger.info(f"{res_url} files will be downloaded into {local_cache_path}")
        client.feathr_spark_launcher.download_result(result_path=res_url, local_folder=local_cache_path)

```

Regarding using spark, one can pass the `spark` session argument to this function to explicitly call spark version and get spark's DataFrame as the result. We also have more explicit alias, `get_result_spark_df`.
 
I'm closing this issue but feel free to re-open and add comments if we have different expected behavior of this function.
